// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvnB8MtHt1QeJ_JW29HwajxHm57oXjG70',
    appId: '1:895658009924:web:783b116e37db7e67142311',
    messagingSenderId: '895658009924',
    projectId: 'bluepay-d2fcf',
    authDomain: 'bluepay-d2fcf.firebaseapp.com',
    storageBucket: 'bluepay-d2fcf.appspot.com',
    measurementId: 'G-QDSNQB5PHH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtlGqFedF7m533gAc3ZV4b1aRXj22LudQ',
    appId: '1:895658009924:android:1ea040f01e41949f142311',
    messagingSenderId: '895658009924',
    projectId: 'bluepay-d2fcf',
    storageBucket: 'bluepay-d2fcf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsxB3PcT-BEtxsPYzZFTUA9PCXGBd5JAM',
    appId: '1:895658009924:ios:66e36dd562a2329c142311',
    messagingSenderId: '895658009924',
    projectId: 'bluepay-d2fcf',
    storageBucket: 'bluepay-d2fcf.appspot.com',
    iosBundleId: 'com.example.wallet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsxB3PcT-BEtxsPYzZFTUA9PCXGBd5JAM',
    appId: '1:895658009924:ios:d439ba388d64d36e142311',
    messagingSenderId: '895658009924',
    projectId: 'bluepay-d2fcf',
    storageBucket: 'bluepay-d2fcf.appspot.com',
    iosBundleId: 'com.example.wallet.RunnerTests',
  );
}
